version: "3.5"
services:
    mysql:
        build: ./requirements/mariadb/
        image: mariadb
        container_name: mysql
        volumes:
            - "mariadb-db:/var/lib/mysql"
        env_file:
            - .env
        restart: always
        networks:
            - backend
        expose:
            - 3306
    wordpress:
        build: ./requirements/wordpress/
        image: wordpress
        container_name: wordpress
        volumes:
            - "wordpress-files:/var/www/html"
        depends_on:
            - mysql
        env_file:
            - .env
        networks:
            - frontend
            - backend
        restart: always
        expose:
            - 9000
    nginx:
        build: ./requirements/nginx/
        image: nginx
        container_name: nginx
        ports:
            - 443:443
        volumes:
            - "wordpress-files:/var/www/html"
        depends_on:
            - wordpress
        restart: always
        networks:
            - frontend

networks:
    frontend:
    backend:

volumes:
    wordpress-files:
    mariadb-db:
