version: '3'

services:
    mysql:
        build: ./requirements/mariadb/
        image: my_mariadb_img:latest
        volumes:
            - "mariadb-db:/var/lib/mysql"
        env_file:
            - .env
        restart: always
        expose:
            - 3306
    wordpress:
        build: ./requirements/wordpress/
        image: my_wordpress:latest
        volumes:
            - "wp-test:/var/www/html"
        depends_on:
            - mysql
        env_file:
            - .env
        links:
            - mysql
        restart: always
        expose:
            - 9000
    nginx:
        build: ./requirements/nginx/
        image: my_nginx_img:latest
        ports:
            - 80:80
            - 443:443
        links:
            - wordpress
        volumes:
            - "wp-test:/var/www/html"
        restart: always

volumes:
    wp-test:
    mariadb-db:
