version: '3'

services:
    mysql:
        build: ./requirements/mariadb/
        image: my_mariadb_img
        volumes:
            - "mariadb-db:/var/lib/mysql"
        env_file:
            - .env
        restart: always
        networks:
            - backend
        expose:
            - 3306
    wordpress:
        build: ./requirements/wordpress/
        image: my_wordpress_img
        volumes:
            - "wp-test:/var/www/html"
        depends_on:
            - mysql
        env_file:
            - .env
        networks:
            - frontend
            - backend
        restart: always
        expose:
            - 9000
    nginx:
        build: ./requirements/nginx/
        image: my_nginx_img
        ports:
            - 443:443
        volumes:
            - "wp-test:/var/www/html"
        depends_on:
            - wordpress
        restart: always
        networks:
            - frontend

networks:
    frontend:
    backend:

volumes:
    wp-test:
    mariadb-db:
