FROM debian:buster
ARG DEBIAN_FRONTEND=noninteractive

# Create SSL Certificate
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/C=FR/ST=Paris/L=Paris/O=42/CN=tmorris.42.fr"

# Expose port
EXPOSE 443

